### ISSUE TITLE
Use classnames.js for conditional styling

### ISSUE THREAD

**Issue by matobet** [oVirt/ovirt-ui-components#12]

**Comment by jelkosz** [comment]
What would be the purpose? To clear the current code up or to prepare it to be embedded to different projects? If the latter than I would postpone this effort to the time we will really need it so it will not be a shot in the dark but we will have first hand experience using it (and potentially abandoning if it turns out as not a good fit).

**Comment by matobet** [comment]
@jelkosz it is just a simple utility to clean up the boilerplate such as https://github.com/oVirt/ovirt-ui-components/blob/master/src/components/VmsList/Vms.js#L11 where we use complicated logic to construct the `classNames` object. 

This should have little to none effect on the reusability of those components.

**Comment by sjd78** [comment]
Only the Checkbox component has any logic in its className (https://github.com/oVirt/ovirt-ui-components/blob/master/src/components/Checkbox/index.js#L30).  Using **classnames** would be a bit overkill in this instance.

Checkbox will probably be replaced by [patternfly-react](https://github.com/patternfly/patternfly-react/) components in future anyway.

**Comment by sandrobonazzola** [comment]
Closing as this project is not developed anymore.
